const searchFieldTypes = {
    OPEN_SEARCH_POPUP: 'OPEN_SEARCH_POPUP',
    CLOSE_SEARCH_POPUP: 'CLOSE_SEARCH_POPUP',
    CHANGE_FILTER_TEXT: 'CHANGE_FILTER_TEXT',
    CHANGE_ROUTE_LOCATION: 'CHANGE_ROUTE_LOCATION',
    FETCH_FILTERED_TITLES_START: 'FETCH_FILTERED_TITLES_START',
    FETCH_FILTERED_TITLES_SUCCESS: 'FETCH_FILTERED_TITLES_SUCCESS',
    FETCH_FILTERED_TITLES_FAILURE: 'FETCH_FILTERED_TITLES_FAILURE',
    CLEAR_SEARCH_FIELD: 'CLEAR_SEARCH_FIELD',
    CLEAR_FILTERED_TILES: 'CLEAR_FILTERED_TITLES'
}

export default searchFieldTypes;