const searchFieldTypes = {
    TOGGLE_SEARCH_POPUP_HIDDEN: 'TOGGLE_SEARCH_POPUP_HIDDEN',
    CHANGE_FILTER_TEXT: 'CHANGE_FILTER_TEXT',
    FETCH_FILTERED_TITLES_START: 'FETCH_FILTERED_TITLES_START',
    FETCH_FILTERED_TITLES_SUCCESS: 'FETCH_FILTERED_TITLES_SUCCESS',
    FETCH_FILTERED_TITLES_FAILURE: 'FETCH_FILTERED_TITLES_FAILURE',
    CLEAR_SEARCH_FIELD: 'CLEAR_SEARCH_FIELD',
    CLEAR_FILTERED_TILES: 'CLEAR_FILTERED_TITLES'
}

export default searchFieldTypes;