const summaryActionTypes = {
    FETCH_SUMMARY_START: 'FETCH_SUMMARY_START',
    FETCH_SUMMARY_SUCCESS: 'FETCH_SUMMARY_SUCCESS',
    FETCH_SUMMARY_FAILURE: 'FETCH_SUMMARY_FAILURE',
    FETCH_TITLE_GENRES_START: 'FETCH_TITLE_GENRES_START',
    FETCH_TITLE_GENRES_SUCCESS: 'FETCH_TITLE_GENRES_SUCCESS',
    FETCH_TITLE_GENRES_FAILURE: 'FETCH_TITLE_GENRES_FAILURE',
    FETCH_CHARACRERS_START: 'FETCH_CHARACTERS_START',
    FETCH_CHARACRERS_SUCCESS: 'FETCH_CHARACTERS_SUCCESS',
    FETCH_CHARACRERS_FAILURE: 'FETCH_CHARACTERS_FAILURE',
    CLEAR_SUMMARY_DATA: 'CLEAR_SUMMARY_DATA'
}

export default summaryActionTypes;