const collectionActionTypes = {
    ADD_TITLE_TO_COLLECTION: 'ADD_TITLE_TO_COLLECTION',
    REMOVE_TITLE_FROM_COLLECTION: 'REMOVE_TITLE_FROM_COLLECTION',
    CHANGE_COLLECTION_TITLE: 'CHANGE_COLLECTION_TITLE',
    OPEN_EDIT_MODAL: 'OPEN_EDIT_MODAL',
    CLOSE_EDIT_MODAL: 'CLOSE_EDIT_MODAL'
}

export default collectionActionTypes;