const catalogPreviewActionTypes = {
    FETCH_PREVIEWS_START: 'FETCH_PREVIEWS_START',
    FETCH_PREVIEWS_SUCCESS: 'FETCH_PREVIEWS_SUCCESS',
    FETCH_PREVIEWS_FAILURE: 'FETCH_PREVIEWS_FAILURE',
    CLEAR_PREVIEW_TITLES: 'CLEAR_PREVIEW_TITLES'
}

export default catalogPreviewActionTypes;