const catalogActionTypes = {
    CHANGE_CURRENT_PAGE: 'CHANGE_CURRENT_PAGE',
    SET_CATALOG_MODE: 'SET_CATALOG_MODE',
    SET_MODE_SUBTYPE: 'SET_MODE_SUBTYPE',
    FETCH_TITLES_START: 'FETCH_TITLES_START',
    FETCH_TITLES_SUCCESS: 'FETCH_TITLES_SUCCESS',
    FETCH_TITLES_FAILURE: 'FETCH_TITLES_FAILURE',
    FETCH_GENRES_START: 'FETCH_GENRES_START',
    FETCH_GENRES_SUCCESS: 'FETCH_GENRES_SUCCESS',
    FETCH_GENRES_FAILURE: 'FETCH_GENRES_FAILURE',
    CLEAR_CATALOG_TITLES: 'CLEAR_CATALOG_TITLES'
}

export default catalogActionTypes;